enum AuthFormActionKind {
  SUCCESS_FORM_FIRST = 'SUCCESS_FORM_FIRST',
  SUCCESS_FORM_SECOND = 'SUCCESS_FORM_SECOND',
  IS_LOADING = 'IS_LOADING',
  IS_LOADING_SUCCESS = 'IS_LOADING_SUCCESS',
  ERROR_MESSAGE = 'ERROR_MESSAGE',
  SUCCESS_FORM = 'SUCCESS_FORM',
}

export default AuthFormActionKind
