import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Button from 'antd/lib/button/button'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <Button key={1} name="Button">
            Button
          </Button>
        </h1>
      </main>

      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    </div>
  )
}

export default Home
